spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://192.168.1.105:3306/shopping_mall?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ysp750421
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com
    username: 3119395617@qq.com
    password: nwhoxxsuwhniddjj
    default-encoding: utf-8

  servlet:
    multipart:
     max-file-size: 10MB
     max-request-size: 10MB

server:
#  servlet:
#    context-path: /static/**
  tomcat:
    uri-encoding: utf-8
  port: 8080

